import type { Metadata } from "next";
import { figtree, azeretMono } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Baruch Full Stack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} ${azeretMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
