import type { Metadata } from "next";
import { ubuntu, azeretMono } from "./fonts";
import "./globals.css";
import { GlobalNavigation } from "@/components/GlobalNavigation";

export const metadata: Metadata = {
  title: "Baruch Full Stack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} ${azeretMono.variable} antialiased`}
      >
        <GlobalNavigation />
        {children}
      </body>
    </html>
  );
}
